### ISSUE TITLE
Test cases in Common Tests is not ignored by default

### ISSUE THREAD

**Issue by vkatsuba** [AdRoll/rebar3_hank#113]
Hi All,

Not sure if this correct but by default exported test cases what included into [all()](https://erlang.org/doc/apps/common_test/basics_chapter.html#external-interfaces) function is not ignored. Eg test case `hallo(_Config) -> ok.` looks like should be ignored if this function is exported and added into group tests etc.

Regards,
--V

**Comment by elbrujohalcon** [comment]
Yeah. We tend to add an ignore rule for this to our rebar.config in every project. Maybe it's time to just ignore these things by default already.

**Comment by elbrujohalcon** [comment]
On the other hand, if you're using a modern-enough version of OTP (one that includes 
@paulo-ferraz-oliveira's erlang/otp#2794) you can simply add `-behavior(ct_suite).` to all your suites and be done with it :)

**Comment by elbrujohalcon** [comment]
> a modern-enough version of OTP

It's included in OTP 23.2+

**Comment by elbrujohalcon** [comment]
@pbrudnick @diegomanuel:
Before OTP 23.2 (where there is no need to ignore anything), the only way I can think to figure out if a module _is a common test suite_ and therefore its functions shouldn't be checked by the `unnecessary_function_arguments` rule is to check if it's called `*_SUITE`.

Do you think that's an acceptable ignore rule to add? It will be similar to the one in `unused_configuration_options` to ignore `elvis.config`, `rebar.config`, etc.

What's your take on this?
