### ISSUE TITLE
The `{unused_callbacks, cb_func_name_to_ignore}` is not working

### ISSUE THREAD

**Issue by vkatsuba** [AdRoll/rebar3_hank#114]
Hi All,

Not sure but looks like `{unused_callbacks, cb_func_name_to_ignore}` is not working, I'm try put for ignore some callback function from `optional_callbacks` and looks like this is not working for me. Tried constructions:
```erlang
-hank([{unused_callbacks, callback_func_name}]).
```
```erlang
-hank([{unused_callbacks, callback_func_name/1}]).
```
```erlang
-hank([{unused_callbacks, [callback_func_name/1]}]).
```
```erlang
-hank([{unused_callbacks, [callback_func_name]}]).
```
Only `-hank([unused_callbacks]).` is working as expected.

Regards,
--V

**Comment by elbrujohalcon** [comment]
It's correct. It was not implemented yet. Its implementation will be part of #84.

**Comment by vkatsuba** [comment]
Closed as duplicate.
