### ISSUE TITLE
Extend doc on NIFs and unnecessary_function_arguments

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_hank#142]
We need to add a part to the note stating that we _assume_ that when implementing a NIF stub, `erlang:nif_error/1,2` will be called.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, look: https://github.com/tsloughter/rebar3_run/pull/15/files#diff-82164c31c03717109e0ad73cca938d80878d9e52901255d9b068f3d83e629f39L56.

Guess where that change came from 😄
