### ISSUE TITLE
Un-require previous rule exclusion

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_hank#144]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when, after fixing an issue that `hank` was complaining about, and for which I created an exclusion rule, which I finally do a fix (e.g. I start using that argument that I wasn't), and `hank` doesn't warn me that the previous exclusion is not required anymore.

## Describe the solution you'd like
Hank telling me about unused exclusions.

## Describe alternatives you've considered
I've only ever considered removing an exclusion, running it again, and figuring out if it's complaining, but that doesn't seem very good as a process.

## Additional Context
I know this might not be easy to implement, but am opening it as a feature request in case the maintainers hadn't discussed it yet.

**Comment by elbrujohalcon** [comment]
Well... The unused exclusion is, in fact, _Oxbow Code_ and therefore it could be detected by Hank. 😎
We might _just_ need a new rule for this. 🤔

**Comment by paulo-ferraz-oliveira** [comment]
I like the way you think here. And there, too.

**Comment by pbrudnick** [comment]
Nice, I like it!
