### ISSUE TITLE
Don't analyze files under `.erlang.mk`

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_hank#150]
[erlang.mk](https://erlang.mk/) generates a folder `.erlang.mk` and it includes tons of `erl`/`hrl` files that hank incorrectly includes in its analysis. We should ignore them.

_Originally posted by @elbrujohalcon in https://github.com/AdRoll/rebar3_hank/issues/149#issuecomment-883968488_

**Comment by pbrudnick** [comment]
Not sure about it, maybe is proper for the user to intentionally ignore folders (the README should help) like that and don't giving ignore support for specific tools.

**Comment by elbrujohalcon** [comment]
It's not a matter of _ignoring it_, @pbrudnick (i.e., the user can add it to the `ignore` list in `rebar.config`). It's a matter of not spending a lot of time analyzing it, when it's clearly not part of the user's project.

**Comment by pbrudnick** [comment]
Makes sense! 👍
