### ISSUE TITLE
Crash upon unconventional `.config` file

### ISSUE THREAD

**Issue by g-andrade** [AdRoll/rebar3_hank#157]
(Great lib, by the way!)

## Bug Description
I've got this `.config` file containing a map (in Erlang syntax) and a `.` at the end.

[`file:consult/1`](http://erlang.org/doc/man/file.html#consult-1) can read it fine but Hank crashes when validating `unused_configuration_options`

## To Reproduce
1. Create a file named `crash.config`, with content `#{foobar => 3.14}.`, under a project that uses `rebar_hank` (sorry for the extra work, GitHub does not allow `.config` files to be attached)
2. Invoke `rebar3 hank` on said project and confirm the crash
3. Open an Erlang shell and see how `file:consult("crash.config")` succeeds by comparison

## Expected Behavior
I expected it to not crash (but nothing in particular beyond that, as I was unaware of the `unused_configuration_options` check until this happened.)

## `rebar3` Logs
[hank crash log.txt](https://github.com/AdRoll/rebar3_hank/files/6957550/hank.crash.log.txt)

## Additional Context
 - OS: macOS Big Sur 11.4
 - Erlang/OTP version 22.3.4.20
 - rebar3 version 3.15.2
 - `rebar3_hank` version: 1.1.4

**Comment by g-andrade** [comment]
The crash is happening [right here](https://github.com/AdRoll/rebar3_hank/blob/1.1.4/src/rules/unused_configuration_options.erl#L87), presumably because `ConfigTuples` is not a list.

Therefore the fix looks superficially easy, but that depends on what counts as a valid `.config` file. Is it anything that `file:consult/1` can parse? Or is its definition stricter?

**Comment by g-andrade** [comment]
> Is it anything that file:consult/1 can parse? Or is its definition stricter?

[The documentation](https://erlang.org/doc/man/config.html) doesn't explicitly restrict it, but it does sort of suggest it's the latter. 

So it's possible I should just not use `.config` as an extension in my use case, albeit somewhat inconvenient (I've got Erlang syntax highlighting setup for it.)

What do you think?

**Comment by elbrujohalcon** [comment]
I think Hank should just ignore files that can't be properly parsed.

But I also think that using a different extension in your case will help you reduce the number of potential issues with different tools that (maybe incorrectly) assume that all `.config` files are formatted as `sys.config` (like Hank and `rebar3_format`, for instance).

**Comment by elbrujohalcon** [comment]
Will be fixed in next release, @g-andrade.
Thanks for spotting the issue!

**Comment by g-andrade** [comment]
👍 Thanks for the quick response!
