### ISSUE TITLE
Implement specific Items ignore for remaining rules

### ISSUE THREAD

**Issue by diegomanuel** [AdRoll/rebar3_hank#84]
After issue #68 and PR #83 in where support to ignore specific rule items were added, the `ignored/2` callback was only implemented for `unnecessary_function_arguments` rule so far.
The other rules just have a default/fallback implementation that keeps the original functionallity working.

This ticket is to complete the `ignored/2` implementation for remaining rules.
**NOTE:** Remember to also add the `@doc` for each rule's "ignore specs".

**Comment by elbrujohalcon** [comment]
The rules with missing implementations are…

- [ ] `single_use_hrl_attrs`
- [ ] `unused_callbacks`
- [ ] `unused_macros`
- [ ] `unused_record_fields`
