### ISSUE TITLE
The directive to ignore a check on a module doesn't seem to work

### ISSUE THREAD

**Issue by facundoolano** [AdRoll/rebar3_hank#87]
## Bug Description
I tried adding
```erl
-hank([unnecessary_function_arguments]).
```
As well as other variants, [as described in the README](https://github.com/AdRoll/rebar3_hank#ignore-specific-rule-items), but they don't seem to cause hank to ignore the check of unused parameters.

Adding the module path to the ignore option in rebar.config does seem to work.

## To Reproduce
Add a function with unused parameters and try to ignore them by setting `-hank([unnecessary_function_arguments]).` in the module.

## Expected Behavior
Hank doesn't report an error for that module.

## Additional Context
macOS
rebar 3.14.2 on Erlang/OTP 22 Erts 10.7.2.1

**Comment by pbrudnick** [comment]
Seems to be a regression bug after https://github.com/AdRoll/rebar3_hank/pull/83

Modifying this line to `-hank([unused_macros]).` make tests fail.

**Comment by elbrujohalcon** [comment]
The rule is not yet called unnecessary_function_arguments. That's for the next release of hank.
In 0.2.1, it's called unused_ignored_function_params.

**Comment by diegomanuel** [comment]
Hey @facundoolano thanks for reporting the issue!
We have changes to be released soon for `0.3.0` that includes support to ignore specific items (#83), but it's not available yet at `0.2.1`.
As Brujo said, it should work with the old/original rule name:
`-hank([unused_ignored_function_params]).`

Please let us know if that solves the issue, thanks again!
